import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/cmps/Navbar/Navbar";
import InteractiveComponent from "@/cmps/Test";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <InteractiveComponent />
      <body >{children}</body>
    </html>
  );
}
